### ISSUE TITLE
View and Download animations on Gadi/ARE

### ISSUE THREAD

**Issue by max-anu** [ACCESS-NRI/ACCESS-Vis#16]
When animations are made, Jupyter notebooks on Gadi are unable to display them and you are unable to directly download them using its button.

Error message: "No video with supported format and MIME type found."

Example code:
```
lv = accessvis.plot_earth(waves=True, when=dt, blendtex=True, vertical_exaggeration=15, sunlight=False)

#Shading/colour/lighting settings
lv.brightness_contrast_saturation(0.5, 0.525, 0.45)

#Setup lighting
lv.set_properties(diffuse=0.4, ambient=0.65, specular=0.4, shininess=0.045, light=[1,1,0.98,1])

#Northern hemisphere view for snow
lv.translation(0.0, 0.0, -16.75)
lv.rotation(40.775, -38.462, -21.42)


rinc = 0.02

filename = os.path.abspath('seasons.mp4')
print(f'Saving to {filename}')

with lv.video(filename=filename, quality=3, resolution=(1440,1440), width=1440//2, height=1080//2, params="autoplay") as v:    
    step = 4 #2
    for d in tqdm(range(0,366,step), desc='Day'):
        dt = datetime.datetime.strptime(f'04 {str(d+1).zfill(3)} 12:00', '%y %j %H:%M')
        dt = dt.replace(tzinfo=datetime.timezone.utc)
        accessvis.update_earth_datetime(lv, when=dt, sunlight=True)
        lv["title"] = '+' + dt.strftime("%d/%m/%Y")
        lv.rotate('y', rinc) #Rotate about axis too
        lv.render()

    #Final frames
    for f in range(30):
        lv.rotate('y', rinc)
        lv.render()
```

**Comment by OKaluza** [comment]
This is because jupyterlab on gadi doesn't support /files, if you run jupyter anywhere else you can access files this way but whichever implementation is used there doesn't allow it, I'll look into it

**Comment by OKaluza** [comment]
Actually that wasn't true, you can access individual files via /files on gadi if you have the correct path.
The problem is the notebook's working directory on gadi is not set to the same dir as the open notebook, this seems crazy to me and it doesn't work like this elsewhere but should be solvable.

**Comment by OKaluza** [comment]
This should be fixed now with updates to lavavu, I'll release a new version today so the conda env can be updated
https://github.com/lavavu/LavaVu/commit/b724660b382105309e04d29fe5de0c102fce1a32
https://github.com/lavavu/LavaVu/commit/51858cde521cadcf80c7ade4a38a8c2ea50d1f2f

**Comment by OKaluza** [comment]
Another different approach to fix this, this time tested and working on gadi ARE https://github.com/lavavu/LavaVu/commit/734d44720e5e02aebbb40c99f280c48833c381ad and following commits etc
That global working directory on ARE is a real PITA, I don't know why the working directory can't be set to the active notebook like it is in every other jupyterlab instance I've ever used, way too much time wasted on this.

**Comment by rbeucher** [comment]
I have just tried this on ARE with the new version of Lavavu 1.8.83 and I still can't view/download the animation.
This is with conda/access-med-0.9 environment.

**Comment by OKaluza** [comment]
It expects a relative path here https://github.com/ACCESS-NRI/ACCESS-Visualisation-Recipes/commit/6928b3a628eaddaba2a45e81ba63ccc8fb42dab2
Also fixed in lavavu to handle absolute paths because the jupyter web server will not like them https://github.com/lavavu/LavaVu/commit/ef4879118a366014fe3e2dac2de315dc524709f4

**Comment by OKaluza** [comment]
See also, relpath used for all links now https://github.com/lavavu/LavaVu/commit/3ced473c3e942810e14107cbc33432f9e9c89946 will be in next lavavu release
I still suggest avoiding abspath for the video filename

**Comment by max-anu** [comment]
I was having issues because it was looking for the file in the wrong folder. You must change your current working directory. 
This an be done when creating a notebook by adding the Extra arguments: `--notebook-dir=/g/data/<project>/<user>/ACCESS-Visualisation-Recipes`
I added warnings stating this [here](https://github.com/ACCESS-NRI/ACCESS-Visualisation-Recipes/pull/15)

**Comment by OKaluza** [comment]
Yes the core issue is related to determining where the output file ends up in relation to the jupyter notebook url, so if you override notebook-dir it won't crop up, but that is not the solution as you should not need to do this IMO. It should work regardless of notebook-dir.
Currently I can't duplicate the issue as it works for me, even without setting notebook-dir, except for those examples which passed an absolute path as the output filename, which is never going to be supported as the jupyter web server can't serve a file from an absolute path.
